### ISSUE TITLE
NullPointerException on ShowMapActivity

### ISSUE THREAD

**Issue by hubbardgary** [hubbardgary/LondonTrails#1]
The following error is regularly appearing in the Developer Console error logs:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2927)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2988)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1631)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.NullPointerException: 
  at com.hubbardgary.londontrails.viewmodel.ShowMapViewModel.<init> (ShowMapViewModel.java:17)
  at com.hubbardgary.londontrails.presenter.ShowMapPresenter.<init> (ShowMapPresenter.java:24)
  at com.hubbardgary.londontrails.view.ShowMapActivity.setUpMap (ShowMapActivity.java:233)
  at com.hubbardgary.londontrails.view.ShowMapActivity.setUpMapIfNeeded (ShowMapActivity.java:228)
  at com.hubbardgary.londontrails.view.ShowMapActivity.onCreate (ShowMapActivity.java:110)
  at android.app.Activity.performCreate (Activity.java:6942)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2880)
```

Reported on a variety of devices including Galaxy S5/S6/S8, Pixel XL and Xperia Z5 Compact.

**Comment by hubbardgary** [comment]
This happens when a user navigates to the ShowMap activity, then presses Home, and doesn't return to the app for a while. In the meantime, Android might kill the LondonTrails app to free up memory. This destroys everything in the Application object, including all the GlobalObjects that have been set up. When the user returns to LondonTrails, Android recreates the Application object and tries to restart the activity the user was on. The problem is the Route no longer exists, and this causes the NullPointerException.

This can be reproduced by going to Developer Options and setting Background Process Limit to "No background processes". Then navigate to the ShowMap activity, switch to a different app, then switch back to LondonTrails. The following error appears in logcat:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.hubbardgary.londontrails, PID: 19527
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hubbardgary.londontrails/com.hubbardgary.londontrails.view.ShowMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hubbardgary.londontrails.model.Route.getName()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2733)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6321)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hubbardgary.londontrails.model.Route.getName()' on a null object reference
                      at com.hubbardgary.londontrails.viewmodel.ShowMapViewModel.<init>(ShowMapViewModel.java:17)
                      at com.hubbardgary.londontrails.presenter.ShowMapPresenter.<init>(ShowMapPresenter.java:24)
                      at com.hubbardgary.londontrails.view.ShowMapActivity.setUpMap(ShowMapActivity.java:233)
                      at com.hubbardgary.londontrails.view.ShowMapActivity.setUpMapIfNeeded(ShowMapActivity.java:228)
                      at com.hubbardgary.londontrails.view.ShowMapActivity.onCreate(ShowMapActivity.java:110)
                      at android.app.Activity.performCreate(Activity.java:6760)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6321) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
W/ActivityManager:   Force finishing activity com.hubbardgary.londontrails/.view.ShowMapActivity
D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{246e9da u0 Starting com.hubbardgary.londontrails} token=android.os.Binder@f681057 which=1
I/ActivityManager: Process com.hubbardgary.londontrails (pid 19527) has died
I/ActivityManager: Start proc 19596:com.hubbardgary.londontrails/u0a204 for activity com.hubbardgary.londontrails/.view.RouteOptionsActivity
```

More info [here](http://www.developerphil.com/dont-store-data-in-the-application-object/) and [here](https://medium.com/inloop/android-process-kill-and-the-big-implications-for-your-app-1ecbed4921cb).
